# Generated by Django 5.0.3 on 2025-03-02 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='complaint',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('street_light', 'Street Light'), ('ghanta_gadi', 'Ghanta Gadi'), ('waste_water', 'Waste Water'), ('road', 'Road')], default='General', max_length=50),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ward_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ComplaintImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaints/images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='complaints.complaint')),
            ],
        ),
    ]
