# Generated by Django 5.0.3 on 2025-03-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_subject_remove_complaint_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintimage',
            name='image',
            field=models.ImageField(upload_to='complaints_images/'),
        ),
    ]
