# Generated by Django 5.0.3 on 2025-03-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaintimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
